CREATE TABLE IF NOT EXISTS Users (
    userID SERIAL PRIMARY KEY,
    pseudo VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL,
    mdp VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Report (
    reportID SERIAL PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    espece VARCHAR(60) NOT NULL,
    nombre INT NOT NULL,
    ville VARCHAR(50) NOT NULL,
    date_pub TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userID INT NOT NULL REFERENCES Users(userID)
);